### ISSUE TITLE
function RFV - imaginary number

### ISSUE THREAD

**Issue by serenariccitelli** [Julie-Fabre/bombcell#14]
Hi Julie,

When using Hill's equation to calculate refractory period violations, I got sometimes imaginary numbers. I noticed that you somehow solved this issue.
I was wondering how did you get to this equation: nRPVs / (2 * (tauR(iTauR_value) - tauC) * (N_chunk - nRPVs)) and how you usually treat those units.
(I pasted the code below)

if ~isreal(fractionRPVs(iTimeChunk,iTauR_value)) % function returns imaginary number if r is too high: overestimate number.
            overestimateBool(iTimeChunk,iTauR_value) = 1;
            if nRPVs < N_chunk %to not get a negative wierd number or a 0 denominator
                fractionRPVs(iTimeChunk,iTauR_value) = nRPVs / (2 * (tauR(iTauR_value) - tauC) * (N_chunk - nRPVs));
            else
                fractionRPVs(iTimeChunk,iTauR_value) = 1;
            end
        end

Thanks,
Sere

**Comment by serenariccitelli** [comment]
indeed in the [UltraMegaSort 2000](https://neurophysics.ucsd.edu/lab/UltraMegaSort2000%20Manual.pdf) they do not subtract  nRPVs from the total amount of spikes (N_chunk - nRPVs) in order to calculate the total amount of time in which an RPV could occur.

**Comment by Julie-Fabre** [comment]
Hi Sere, 
Yes, the Hill et al equation (`number_of_refractory_period_violations = 2*(tauR - tauC) * number_of_spikes^2 * (1-refractory_period_violation_rate) * refractory_period_violation_rate / T`, solving for the refractory_period_violation_rate) returns an imaginary number if r, the number of refractory period violations, is too high.
In those cases, I have chosen to overestimate the number of refractory period violations. I divide the number of refractory period violations by the total time available for refractory period violations: `2 * (tauR - tauC) * (number_of_spikes - number_of_refractory_period_violations)`. 
I have chosen to subtract the number_of_refractory_period_violations from the number of spikes to give a more accurate estimate, since you need to remove the number of refractory period violation from the total spike count to get the number of "real" spikes. This method is more conservative and will yield higher numbers than the UltraMegaSort one.

**Comment by Julie-Fabre** [comment]
Hi Sere, if you have no more comments I will close this issue
