### ISSUE TITLE
Bombcell drift correction

### ISSUE THREAD

**Issue by jafardm** [Julie-Fabre/bombcell#164]
Hi Julie,
Thanks for the great work on the Bombcell. I am curious what part of the algorithm handle the drift. It happens in our recording that a unit is stable for good amount of time across the recording, however it might be unstable for short period. That would be good, if we a vector showing the interval that the cell is not stable, then we can exclude that specific part for the the rest of the processing. 
Thank you!

**Comment by Julie-Fabre** [comment]
Hi Jafar,

Thank you for your message! Currently, (if param.computeDrift is true /
equals 1) bombcell only outputs two values per unit:
- qMetric.maxDriftEstimate (the maximum absolute drift across the recording
session, in micrometers)
- qMetric.cumDriftEstimate (the cumulative drift across the recording
session, in micrometers)
It's a great idea to output the full trace over time, in order to post hoc
select certain time chunks with low drift for each unit. We will work on
this, but it will not be immediate. In the meantime, you can modify the
following function (bc.qm.maxDriftEstimate
<https://github.com/Julie-Fabre/bombcell/blob/main/%2Bbc/%2Bqm/maxDriftEstimate.m>)
to do that (and, if you do, then please submit a pull request / send your
changes over so we can integrate them to the main pipeline). I will leave
this issue open until we've implemented this new feature.

**Comment by Julie-Fabre** [comment]
Hi Jafar, 

Bombcell now saves the median drift per time chunk (defined in param.driftBinSize) for each unit. There are two new outputs to the function `bc.qm.maxDriftEstimate`: `median_spikeDepth`, `timeBins`. These are saved in two parquet files: `templates._bc_medianSpikeDepth.parquet` (which is a nUnits x nTimechunk table of median drift values) and `time_chunks._bc_medianSpikeDepth.parquet` (which tells you the edges of the timebins) 

You can also modify the code further if you want to save the exact position for every spike of every unit, but we currently aren't doing this as it generates large files. I've added a another optional output in the function `bc.qm.maxDriftEstimate`: `spikeDepths_inChannels` which gives you this information.

**Comment by jafardm** [comment]
Hi Julie,
This is great, Thank you so much.

**Comment by liumy2333** [comment]
@Julie-Fabre Hi Julie, thanks for the updates! I tried this updated code on python but it did not generate the templates._bc_medianSpikeDepth.parquet or time_chunks._bc_medianSpikeDepth.parquet files. I wonder if this updates only applies to MATLAB? Although I doubt, since I did see the updated return in the python function, but no files outputs.
