### ISSUE TITLE
Questions about bombcell

### ISSUE THREAD

**Issue by pseudojulie** [Julie-Fabre/bombcell#247]
Questions submitted by email: 
- It’s possible that the information is already out there, but do you have a set of papers/references I could check out to familiarize myself with the various quality metrics you use? I have seen references to Hill et al. vs. Llobet et al. in the code but am having a hard time finding those papers on Google Scholar without knowing the titles.
- Some parameters are in units of samples (e.g., “waveformBaselineNoiseWindow”) and have hard-coded default values (e.g., for KS4 the parameter “spikeWidth” defaults to 61, “waveformBaselineNoiseWindow” defaults to 10, “waveformBaselineWindowStart” defaults to 1, and “waveformBaselineWindowStop” defaults to 11). Plexon’s PL2 files are recorded at 40 kHz (unlike NeuroPixels’ 30 kHz) and so this will impact the actual duration measured by these parameters. Is there a way to make things more generalizable? Do you suggest updating these values before running BombCell on data derived from a PL2 file?
- The code seems geared towards the use of SpikeGLX probes. Plexon’s recording platform (OmniPlex) supports the use of SiNAPS probes. I am uncertain how this will affect parameters like “probeType”.
- The default value for “duplicateSpikeWindow_s” is 0.00001 seconds. Could you please help me to understand the significance of this value?
- I notice there is a parameter called “nRawSpikesToExtract” and its default value is 100. Based on my reading of +bc/+helpers/extractRawWaveformsFast.m, am I correct in saying that you select the first 100 spikes for each template?
- Do you have a good reference for understanding presence ratios?
- What does the parameter “nSyncChannels” represent? I want to understand whether (and how) this parameter will impact analysis of data recorded with SiNAPS probes.
- What does the parameter “gain_to_uV” represent? In Plexon’s PL2 format, electrophysiological data are actually stored as int16’s. We provide a coefficient multiplier for converting these to floats. Is gain_to_uV where we would feed in this coefficient, or does the parameter serve some other purpose?

**Comment by pseudojulie** [comment]
Thank you for your message!

> - It’s possible that the information is already out there, but do you have a set of papers/references I could check out to familiarize myself with the various quality metrics you use? I have seen references to Hill et al. vs. Llobet et al. in the code but am having a hard time finding those papers on Google Scholar without knowing the titles.
> - Do you have a good reference for understanding presence ratios?

Here's a table of all the quality metrics and refs - some don't have refs because we've developed them (in orange) or they are pretty agreed-upon (blue). 

<google-sheets-html-origin></style>
Quality metric | Bombcell name | Used to classify... | Reference
-- | -- | -- | --
Number of waveform peaks | qMetric.nPeaks | Noise | I don't have references that use this as a quality metric but this a pretty agreed-upon metric Note that in some brain regions like the cerebellum, some units can have atypical waveform shapes and the default classificatio parameters need to be tweaked.
Number of waveform troughs | qMetric.nTroughs | Noise | See above
Waveform duration | qMetric.waveformDuration_peakTrough | Noise | I don't have references that use this as a quality metric but this a pretty agreed-upon metric
Spatial decay | qMetric.spatialDecaySlope | Noise | We developed this metric. Depending on geometry. it might not be calculated (it makes sense to caclulate this for high-density probes, but otherwise is useless. Bombcell automatically checks if the probe geometry allows it or not.)
Waveform baseline flatness | qMetric.waveformBaselineFlatness | Noise | We developed this metric. It is piurely empirical: we found that a lot of noise units had this characteristic.
Repolarization-peak' to trough ratio | qMetric.scndPeakToTroughRatio_noise | Noise | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
Main peak'-to-trough ratio | qMetric.mainPeakToTroughRatio_non_somatic | Non-somatic | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
First peak'-to-'repolarization peak ratio | qMetric.peak1ToPeak2RatioRatio_non_somatic | Non-somatic | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
Number of spikes | qMetric.nSpikes | MUA | This is not reallty a quality-metric per se, but we need a certain minimum number of spikes to compute reliable spike-based metrics so it is a prerequisite.
Percentage spikes missing | qMetric.percentageSpikesMissing_gaussian | MUA | This metric is based on a phy plugin (https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/views/amplitude_histogram.py). It is also used in this study: https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522/3
Refractory period violations | qMetric.fractionRPVs_estimatedTauR | MUA | There are two options. Hill: https://pubmed.ncbi.nlm.nih.gov/21677152/ or Llobet (more accurate, but slower): https://www.biorxiv.org/content/10.1101/2022.02.08.479192v1
Presence ratio | qMetric.presenceRatio | MUA | Inspired by Seigle et al: https://www.nature.com/articles/s41586-020-03171-x
Drift estimate | qMetric.maxDrift | MUA | Seigle et al: https://www.nature.com/articles/s41586-020-03171-x
Mean raw waveform amplitude | qMetric.rawAmplitude | MUA | We have found this correlates well with unit isolation, and works better than the distance metrics (isolation distance and L-ratio) in cases of electrode drift (as is often the case)
Signal-to-noise ratio | qMetric.signalToNoiseRatio | MUA | I don't have references that use this as a quality metric but this a pretty agreed-upon metric
Isolation distance | qMetric.isoD | MUA | Disabled by default because it does not fare well in cases of large drift. Harris et al: https://pubmed.ncbi.nlm.nih.gov/11604145/
L-ratio | qMetric.Lratio | MUA | Disabled by default because it does not fare well in cases of large drift. Schmitzer-Torbert et al: https://www.sciencedirect.com/science/article/pii/S0306452204008425

The presence ratio is the fraction of time chunks that contain recordings from this unit, with a chunk considered "present" if it has at least 5% of the maximum spike count seen in any chunk. It is to estimate what fraction of the recording time a unit was present. 
There are some more explanations of each metric here: https://github.com/Julie-Fabre/bombcell/wiki/Detailed-overview-of-quality-metrics#mean-raw-waveform-amplitude 

> - Some parameters are in units of samples (e.g., “waveformBaselineNoiseWindow”) and have hard-coded default values (e.g., for KS4 the parameter “spikeWidth” defaults to 61, “waveformBaselineNoiseWindow” defaults to 10, “waveformBaselineWindowStart” defaults to 1, and “waveformBaselineWindowStop” defaults to 11). Plexon’s PL2 files are recorded at 40 kHz (unlike NeuroPixels’ 30 kHz) and so this will impact the actual duration measured by these parameters. Is there a way to make things more generalizable? Do you suggest updating these values before running BombCell on data derived from a PL2 file? 

 The length of these baselines don't matter, they just need to be at least 0.15ms before the start of your waveform. I assume you are kilosorting your data - if so just take the default depending on the kilosort version.

> - What does the parameter “gain_to_uV” represent? In Plexon’s PL2 format, electrophysiological data are actually stored as int16’s. We provide a coefficient multiplier for converting these to floats. Is gain_to_uV where we would feed in this coefficient, or does the parameter serve some other purpose?
> - The code seems geared towards the use of SpikeGLX probes. Plexon’s recording platform (OmniPlex) supports the use of SiNAPS probes. I am uncertain how this will affect parameters like “probeType”.

The probeType parameter is there purely if there are errors reading spikeGLKX meta files, so we can still get the correct "gain_to_uV" scaling (this is the scaler, that when multiplied by your raw data in bits gives you data in microVolts.) Ignore this and only set the param.gain_to_uv to the correct value for your probes. If you tell me what it is and how to detect your probe type, I can also add this value in directly :)

> - What does the parameter “nSyncChannels” represent? I want to understand whether (and how) this parameter will impact analysis of data recorded with SiNAPS probes.
This value represents any channels that don't contain neural data but rather some other experimental/synchronization data. If you have no channels like this in your raw file, set it to zero. 

> - The default value for “duplicateSpikeWindow_s” is 0.00001 seconds. Could you please help me to understand the significance of this value?

Spike-sorters (including kilosort) can sometimes count spikes twice if for instance the residuals are re-fitted. see https://github.com/MouseLand/Kilosort/issues/29. Bombcell detects any spikes that are suspiciously at exactly the same time and removes the duplicates. You can disable this if you like by setting param.removeDuplicateSpikes to false/0. 

> - I notice there is a parameter called “nRawSpikesToExtract” and its default value is 100. Based on my reading of +bc/+helpers/extractRawWaveformsFast.m, am I correct in saying that you select the first 100 spikes for each template?

Yes, that is correct. A better way would be to randomly sample spikes - feel free to implement that if you like and submit a pull request :).

**Comment by Julie-Fabre** [comment]
Thank you for your message!

> - It’s possible that the information is already out there, but do you have a set of papers/references I could check out to familiarize myself with the various quality metrics you use? I have seen references to Hill et al. vs. Llobet et al. in the code but am having a hard time finding those papers on Google Scholar without knowing the titles.
> - Do you have a good reference for understanding presence ratios?

Here's a table of all the quality metrics and refs - some don't have refs because we've developed them (in orange) or they are pretty agreed-upon (blue). 

<google-sheets-html-origin></style>
Quality metric | Bombcell name | Used to classify... | Reference
-- | -- | -- | --
Number of waveform peaks | qMetric.nPeaks | Noise | I don't have references that use this as a quality metric but this a pretty agreed-upon metric Note that in some brain regions like the cerebellum, some units can have atypical waveform shapes and the default classificatio parameters need to be tweaked.
Number of waveform troughs | qMetric.nTroughs | Noise | See above
Waveform duration | qMetric.waveformDuration_peakTrough | Noise | I don't have references that use this as a quality metric but this a pretty agreed-upon metric
Spatial decay | qMetric.spatialDecaySlope | Noise | We developed this metric. Depending on geometry. it might not be calculated (it makes sense to caclulate this for high-density probes, but otherwise is useless. Bombcell automatically checks if the probe geometry allows it or not.)
Waveform baseline flatness | qMetric.waveformBaselineFlatness | Noise | We developed this metric. It is piurely empirical: we found that a lot of noise units had this characteristic.
Repolarization-peak' to trough ratio | qMetric.scndPeakToTroughRatio_noise | Noise | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
Main peak'-to-trough ratio | qMetric.mainPeakToTroughRatio_non_somatic | Non-somatic | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
First peak'-to-'repolarization peak ratio | qMetric.peak1ToPeak2RatioRatio_non_somatic | Non-somatic | We developed this metric. It is inspired by slice recordings from Deligkaris et al. (https://pmc.ncbi.nlm.nih.gov/articles/PMC5021702/) and simulations from Buzsaki (https://www.nature.com/articles/nrn3241)
Number of spikes | qMetric.nSpikes | MUA | This is not reallty a quality-metric per se, but we need a certain minimum number of spikes to compute reliable spike-based metrics so it is a prerequisite.
Percentage spikes missing | qMetric.percentageSpikesMissing_gaussian | MUA | This metric is based on a phy plugin (https://github.com/kwikteam/phy-contrib/blob/master/phycontrib/views/amplitude_histogram.py). It is also used in this study: https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522/3
Refractory period violations | qMetric.fractionRPVs_estimatedTauR | MUA | There are two options. Hill: https://pubmed.ncbi.nlm.nih.gov/21677152/ or Llobet (more accurate, but slower): https://www.biorxiv.org/content/10.1101/2022.02.08.479192v1
Presence ratio | qMetric.presenceRatio | MUA | Inspired by Seigle et al: https://www.nature.com/articles/s41586-020-03171-x
Drift estimate | qMetric.maxDrift | MUA | Seigle et al: https://www.nature.com/articles/s41586-020-03171-x
Mean raw waveform amplitude | qMetric.rawAmplitude | MUA | We have found this correlates well with unit isolation, and works better than the distance metrics (isolation distance and L-ratio) in cases of electrode drift (as is often the case)
Signal-to-noise ratio | qMetric.signalToNoiseRatio | MUA | I don't have references that use this as a quality metric but this a pretty agreed-upon metric
Isolation distance | qMetric.isoD | MUA | Disabled by default because it does not fare well in cases of large drift. Harris et al: https://pubmed.ncbi.nlm.nih.gov/11604145/
L-ratio | qMetric.Lratio | MUA | Disabled by default because it does not fare well in cases of large drift. Schmitzer-Torbert et al: https://www.sciencedirect.com/science/article/pii/S0306452204008425

The presence ratio is the fraction of time chunks that contain recordings from this unit, with a chunk considered "present" if it has at least 5% of the maximum spike count seen in any chunk. It is to estimate what fraction of the recording time a unit was present. 
There are some more explanations of each metric here: https://github.com/Julie-Fabre/bombcell/wiki/Detailed-overview-of-quality-metrics#mean-raw-waveform-amplitude 

> - Some parameters are in units of samples (e.g., “waveformBaselineNoiseWindow”) and have hard-coded default values (e.g., for KS4 the parameter “spikeWidth” defaults to 61, “waveformBaselineNoiseWindow” defaults to 10, “waveformBaselineWindowStart” defaults to 1, and “waveformBaselineWindowStop” defaults to 11). Plexon’s PL2 files are recorded at 40 kHz (unlike NeuroPixels’ 30 kHz) and so this will impact the actual duration measured by these parameters. Is there a way to make things more generalizable? Do you suggest updating these values before running BombCell on data derived from a PL2 file? 

 The length of these baselines don't matter, they just need to be at least 0.15ms before the start of your waveform. I assume you are kilosorting your data - if so just take the default depending on the kilosort version.

> - What does the parameter “gain_to_uV” represent? In Plexon’s PL2 format, electrophysiological data are actually stored as int16’s. We provide a coefficient multiplier for converting these to floats. Is gain_to_uV where we would feed in this coefficient, or does the parameter serve some other purpose?
> - The code seems geared towards the use of SpikeGLX probes. Plexon’s recording platform (OmniPlex) supports the use of SiNAPS probes. I am uncertain how this will affect parameters like “probeType”.

The probeType parameter is there purely if there are errors reading spikeGLKX meta files, so we can still get the correct "gain_to_uV" scaling (this is the scaler, that when multiplied by your raw data in bits gives you data in microVolts.) Ignore this and only set the param.gain_to_uv to the correct value for your probes. If you tell me what it is and how to detect your probe type, I can also add this value in directly :)

> - What does the parameter “nSyncChannels” represent? I want to understand whether (and how) this parameter will impact analysis of data recorded with SiNAPS probes.
This value represents any channels that don't contain neural data but rather some other experimental/synchronization data. If you have no channels like this in your raw file, set it to zero. 

> - The default value for “duplicateSpikeWindow_s” is 0.00001 seconds. Could you please help me to understand the significance of this value?

Spike-sorters (including kilosort) can sometimes count spikes twice if for instance the residuals are re-fitted. see https://github.com/MouseLand/Kilosort/issues/29. Bombcell detects any spikes that are suspiciously at exactly the same time and removes the duplicates. You can disable this if you like by setting param.removeDuplicateSpikes to false/0. 

> - I notice there is a parameter called “nRawSpikesToExtract” and its default value is 100. Based on my reading of +bc/+helpers/extractRawWaveformsFast.m, am I correct in saying that you select the first 100 spikes for each template?

Yes, that is correct. A better way would be to randomly sample spikes - feel free to implement that if you like and submit a pull request :).
