### ISSUE TITLE
Questions about bombcell and NHP

### ISSUE THREAD

**Issue by pseudojulie** [Julie-Fabre/bombcell#248]
Question submitted by slack: 

Hi Julie! I'm xxx, these days I played with some params in BC and I think I find the best combination for my NHP setup, however I still have some queation regarding to use BC as my QC pipeline:
(1) what's the difference between param.extractRaw and param.reextractRaw? I see both of this in qualityParamValues
(2) I use SpikeInterface to pre-process ap file (high-pass, CAR..) and pass it to KS4,  so should I provide the 'ephysRawDir' as ap.bin file from sGLX, or the .bin file saved by spike interface?
(3) I just wan to make sure that, I should set param.nChannels = 385 and param.nSyncChannels = 1 if I do use NPX1 tip bank (384 neural signal, although site-191 is different) and 1 sync channel, and sync channel should be 385 starting from 1, right?
(4) I set param.removeDuplicateSpikes = 1 and the command line told me some duplicate spikes were removed, but how can I find which cluster was removed in BC output? By the way, Looking data in phy, I think there is more residual that was identified as units than BC removed, so is there some parameters that can help me remove residuals more easily and accurately?
Thank you for your help and I'm sorry if I missed any document!

**Comment by Julie-Fabre** [comment]
Thank you for your questions!
(1) param.extractRaw sets whether you want to extract raw waveforms or not. param.reExtractRaw sets whether, if you have already previously extracted waveforms, you want to override that previous extraction and re-extract them.
(2) Either of those work, but the best is to use .bin file saved by spike interface where pre-processing has been performed.
(3) Yes, exactly! As a sanity check, if the waveforms look OK, then you've set it correctly (it is impossible to have good-looking waveforms if these numbers are incorrect). I am going to add an option to directly read these values from the spikeGLX file because a few users have had this question already.
(4)
Could you show me a picture of what you mean in phy?
duplicate spikes removes spikes, and not entire clusters. the removed spikes will be found in spikes._bc_duplicateSpikes.npy
