### ISSUE TITLE
Is param.saveAsTSV already implemented?

### ISSUE THREAD

**Issue by lachioma** [Julie-Fabre/bombcell#25]
Hi Julie

I think that the functionality to save the tsv file to use phy after bombcell is not implemented yet, is it?
https://github.com/Julie-Fabre/bombcell/wiki/Compatibility-with-phy

**Comment by Julie-Fabre** [comment]
Hi lachioma, 

Compatibility with phy was implemented yesterday, due to popular demand. You can see any important changes in bombcell here: https://github.com/Julie-Fabre/bombcell/wiki/Important-changes-log . I am thinking about implementing a mailing list to advertise any new feature additions.

If you pull bombcell again, you should be able to set `param.saveAsTSV` and, when running bombcell again, you will have tsv files that phy automatically loads in. You can also generate them from already saved metrics by setting the `saveTSV` flag to 1 in ` bc_loadSavedMetrics(savePath, saveTSV)`

Let me know if there are any issues!
