### ISSUE TITLE
Unrecognized function or variable 'Vrange' error while running pipeline

### ISSUE THREAD

**Issue by guidomeijer** [Julie-Fabre/bombcell#31]
Hi! Thanks for developing this toolbox, it looks very promising. I'm running into an issue while using it. I'm getting the following error while running the `bc_qualityMetrics_pipeline`:
```
Unrecognized function or variable 'Vrange'.

Error in bc_readSpikeGLXMetaFile (line 54)
scalingFactor = Vrange / (2 ^ bits_encoding) / gain;

Error in bc_getRawAmplitude (line 21)
    scalingFactor = bc_readSpikeGLXMetaFile(metaFile);

Error in bc_runAllQualityMetrics (line 198)
        qMetric.rawAmplitude(iUnit) = bc_getRawAmplitude(rawWaveformsFull(iUnit,rawWaveformsPeakChan(iUnit),:), ...

Error in bc_qualityMetrics_pipeline (line 40)
    [qMetric, unitType] = bc_runAllQualityMetrics(param, spikeTimes_samples, spikeTemplates, ...
```
I tracked it down to the problem that my metadata file does not contain `imDatPrb_type` or `imProbeOpt` so it can't determine the probe type. Here is my metadata content:
```
     acqMnMaXaDw=0,0,1,1
     appVersion=20230815
     fileCreateTime=2023-10-12T12:58:23
     fileName=D:/NeuropixelData/450409/20231012/raw_ephys_data/_spikeGLX_ephysData_g2/_spikeGLX_ephysData_g2_t0.nidq.bin
     fileSHA1=5A87AC275C00486880E99F81E94876AB03263229
     fileSizeBytes=321170604
     fileTimeSecs=2676.1540578326762
     firstSample=265462178
     gateMode=Immediate
     imErrFlags_IS_CT_SR_LK_PP_SY=1 2 0 0 0 0
     nDataDirs=1
     nSavedChans=2
     niAiRangeMax=5
     niAiRangeMin=-5
     niAiTermination=Default
     niClockLine1=Internal
     niClockSource=PXI1Slot2_2_1ch_Int : 30003.000300
     niDev1=PXI1Slot2_2
     niDev1ProductName=PXIe-6341
     niMAChans1=
     niMAGain=1
     niMNChans1=
     niMNGain=200
     niMaxInt=32768
     niMuxFactor=32
     niSampRate=30003.0003
     niStartEnable=false
     niStartLine=PXI1Slot2_2/port0/line0
     niXAChans1=0
     niXDBytes1=1
     niXDChans1=0:7
     snsMnMaXaDw=0,0,1,1
     snsSaveChanSubset=all
     syncNiChan=3
     syncNiChanType=0
     syncNiThresh=1.1
     syncSourceIdx=3
     syncSourcePeriod=1
     trigMode=Immediate
     typeImEnabled=2
     typeNiEnabled=1
     typeObEnabled=0
     typeThis=nidq
     userNotes=
     ~snsChanMap=(0,0,32,1,1)(XA0;0:0)(XD0;1:1)
     ~snsShankMap=(1,2,0)
``` 
I'm using 1.0 probes with SpikeGLX v20230815-phase30.

**Comment by Julie-Fabre** [comment]
Hi Guido, 

That's unexpected. I've never seen a spikeGLX meta file with no field defining the probe type. From the [wiki](https://billkarsh.github.io/SpikeGLX/Sgl_help/Metadata_30.html), there are a lot of fields that should be there, but aren't. It might be useful to raise a github issue there, or write a message on the Neuropixels slack to figure out what's going on. 

For bombcell, I just added an additional parameter in `bc_qualityParamValues`:  `param.probeType`. This paramater is only used if you are using spikeGLX (not open ephys) and probe types are not defined in the meta file. In your case, it should be set like this: `param.probeType = 1;`, since you are using 1.0 probes. If you use 2.0 probes (single or 4shank), you should set the parameter like this: `param.probeType = 2;`

Let me know if you run into any issues!

**Comment by guidomeijer** [comment]
I realized my mistake! I provided the path to the nidq meta data file instead of the probe metadata file. It's working now. There are two .meta files which can be a bit confusing.
