### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by LaurenzMuessig** [Julie-Fabre/bombcell#45]
Hi Julie,

Some small bugs:

- function: 'isMATLABReleaseOlderThan' is missing from repo
- in 'bc_removeDuplicateSpikes' line 71 you'd need to e.g. add _|| ~isnan(pcFeatures)_ to the if statement (at least for me _pcFeatures=NaN_)

Cheers

Laurenz

**Comment by Julie-Fabre** [comment]
Hi Laurenz, 

Thank you for the report! 
- the function [`isMATLABReleaseOlderThan`](https://uk.mathworks.com/help/matlab/ref/ismatlabreleaseolderthan.html) is built-in since 2020b. I guess you are using a MATLAB version older than that. I've modified that part of the script to account for that now. If you are indeed using a MATLAB version older than 2020a, I would recommend downloading and installing a later version.
- Great catch in `bc_removeDuplicateSpikes` - now fixed! 

Cheers

**Comment by LaurenzMuessig** [comment]
Yep. I probably should update my Matlab version...
