### ISSUE TITLE
Issue extracting quality metrics for data spike sorted using Kilosort4

### ISSUE THREAD

**Issue by cameron-woodard** [Julie-Fabre/bombcell#81]
Hello,

I'm running into the following error when trying to extract quality metrics using the pipeline:

Error using  : 
Colon operands must be real scalars.

Error in bc_percSpikesMissing (line 61)
        surrogate_bins = [fliplr(bins(maxAmpli_val_smooth)-bin_steps:-bin_steps:bins(maxAmpli_val_smooth) -
        bin_steps*floor(size(surrogate_amplitudes,2)/2)),...

Error in bc_runAllQualityMetrics (line 118)
        bc_percSpikesMissing(theseAmplis, theseSpikeTimes, timeChunks, param.plotDetails);

Error in bc_qualityMetrics_pipeline (line 51)
    [qMetric, unitType] = bc_runAllQualityMetrics(param, spikeTimes_samples, spikeTemplates, ...

The extracting raw waveforms step runs fine, but this error is thrown in the subsequent step. The pipeline runs perfectly on data sorted with kilosort2.5 and all quality parameters are set to their default value. Please let me know if you have any idea what's causing this issue, or if you require any further information. Thank you!

-Cam

**Comment by Julie-Fabre** [comment]
Hi Cameron, 

Thanks for your message! Are you using a recent version of bombcell? I pushed some changes for kilosort4 ~1 month ago that might be related KS4 saves spikes as singles (rather than doubles) so we convert them with these changes. I also just added more changes to correctly handle template waveforms (which have a different size in KS4). You now have an input `kilosortVersion` you should set to `4` in `bc_qualityParamValues` to get values that make more sense for kilosort4.
Let me know if a more recent version works. If it doesn't, would you be able to send me the following files:
- spike_times.npy
- amplitudes.npy

**Comment by cameron-woodard** [comment]
Ah - that fixed the issue! Should have known better to raise an issue without pulling the latest updates. Thanks for your help.
