### ISSUE TITLE
Maximum waveform channel different between templates and the average extracted waveform.

### ISSUE THREAD

**Issue by anas-masood** [Julie-Fabre/bombcell#97]
Thanks for the amazing tool. I have been trying to use and validate it on our data and I found that the max channel between the templates and the average waveform turn out to be in different places for most deeper cells. Is there a mistake in using kilosort's output templates?

I am using Npx 1.0, and KS version 2.0. 

Normal Behavior:
![image](https://github.com/Julie-Fabre/bombcell/assets/23415375/4001bf23-a7bf-4e9d-af68-85b1e9ee034b)

Abnormal Behavior:
![image](https://github.com/Julie-Fabre/bombcell/assets/23415375/a787ce85-39aa-4ed0-8c11-32f778c550a4)

plot(squeeze(rawWaveforms.average(iCluster, :, :))') reveals there are waveforms present in the channels: 
![image](https://github.com/Julie-Fabre/bombcell/assets/23415375/e1a8cec1-cbb8-4a6f-a2f0-b17d2cb550e9)

However they are not at the chansToPlot : plot(squeeze(rawWaveforms.average(iCluster, chansToPlot, :))')

![image](https://github.com/Julie-Fabre/bombcell/assets/23415375/5678fef1-c515-4e66-9b64-cac8ad0e71ab)

Possible causes: discrepancy between KS2 template max amplitude and average waveform? or is it at the bc_extractAverageWF?

**Comment by Julie-Fabre** [comment]
Hi Anas, 

Thanks a lot for your message! Good catch - KS2 removes "dead channels" from the data, but they are still there in the raw waveforms (because they are extracted directly from the raw file), which can lead to some discrepancies. The quality metrics computed take this into account, but the GUI wasn't displaying this properly. It should now be fixed. Let me know if you run into any more issues or if you have any questions! 

Julie
